STOCKS = [
    {
        "type": "stock",
        "code": "MGLU3",
        "name": "MAGAZINE LUIZA",
        "price": 13.18,
        "sector": "Varejo",
        "volatility": 78.38,
        "dy": 0.0,
        "pvpa": 0.0,
        "appreciation": -53.73,
    },
    {
        "type": "stock",
        "code": "OIBR3",
        "name": "OI",
        "price": 4.67,
        "sector": "Comunicações",
        "volatility": 83.23,
        "dy": 0.0,
        "pvpa": 0.0,
        "appreciation": -21.43,
    },
    {
        "type": "stock",
        "code": "AMER3",
        "name": "AMERICANAS",
        "price": 0.07,
        "sector": "Varejo",
        "volatility": 131.82,
        "dy": 0.0,
        "pvpa": 0.0,
        "appreciation": -92.01,
    },
    {
        "type": "stock",
        "code": "BHIA3",
        "name": "BHIA3",
        "price": 6.22,
        "sector": "Varejo",
        "volatility": 99.20,
        "dy": 0.0,
        "pvpa": 0.0,
        "appreciation": -78.87,
    },
    {
        "type": "stock",
        "code": "PETR4",
        "name": "PETROBRAS PN",
        "price": 37.11,
        "sector": "Minerais Energéticos",
        "volatility": 29.74,
        "dy": 16.15,
        "pvpa": 0.0,
        "appreciation": 45.73,
    },
    {
        "type": "stock",
        "code": "B3SA3",
        "name": "B3",
        "price": 12.54,
        "sector": "Finanças",
        "volatility": 78.38,
        "dy": 5.0,
        "pvpa": 0.0,
        "appreciation": -0.08,
    },
    {
        "type": "stock",
        "code": "LIGT3",
        "name": "LIGHT S/A",
        "price": 5.26,
        "sector": "Utilidades",
        "volatility": 30.92,
        "dy": 3.24,
        "pvpa": 0.0,
        "appreciation": 1.31,
    },
    {
        "type": "stock",
        "code": "MRVE3",
        "name": "MRV",
        "price": 7.17,
        "sector": "Construção Civil",
        "volatility": 52.73,
        "dy": 0.0,
        "pvpa": 0.0,
        "appreciation": -34.15,
    },
    {
        "type": "stock",
        "code": "HAPV3",
        "name": "HAPVIDA",
        "price": 4.37,
        "sector": "Serviços de saúde",
        "volatility": 45.54,
        "dy": 0.0,
        "pvpa": 0.0,
        "appreciation": 2.58,
    },
    {
        "type": "stock",
        "code": "GOLL4",
        "name": "GOL PN",
        "price": 1.09,
        "sector": "Transporte",
        "volatility": 78.38,
        "dy": 79.88,
        "pvpa": 0.0,
        "appreciation": -85.35,
    },
    {
        "type": "stock",
        "code": "AZUL4",
        "name": "AZUL PN",
        "price": 7.45,
        "sector": "Transporte",
        "volatility": 60.85,
        "dy": 0.0,
        "pvpa": 0.0,
        "appreciation": -60.80,
    },
    {
        "type": "stock",
        "code": "ASAI3",
        "name": "ASSAI",
        "price": 9.75,
        "sector": "Varejo",
        "volatility": 41.38,
        "dy": 0.0,
        "pvpa": 0.0,
        "appreciation": -19.47,
    },
    {
        "type": "stock",
        "code": "CVCB3",
        "name": "CVC BRASIL",
        "price": 2.15,
        "sector": "Serviços do Consumidor",
        "volatility": 73.08,
        "dy": 0.0,
        "pvpa": 0.0,
        "appreciation": -20.97,
    },
    {
        "type": "stock",
        "code": "VALE3",
        "name": "VALE",
        "price": 58.38,
        "sector": "Minerais não energéticos",
        "volatility": 21.99,
        "dy": 12.07,
        "pvpa": 0.0,
        "appreciation": 2.40,
    },
    {
        "type": "stock",
        "code": "RAIZ4",
        "name": "RAIZEN PN",
        "price": 3.24,
        "sector": "Varejo",
        "volatility": 34.96,
        "dy": 5.49,
        "pvpa": 0.0,
        "appreciation": -6.65,
    },
    {
        "type": "stock",
        "code": "MRFG3",
        "name": "MARFRIG",
        "price": 14.65,
        "sector": "Bens não duráveis",
        "volatility": 48.16,
        "dy": 0.0,
        "pvpa": 0.0,
        "appreciation": 99.06,
    },
    {
        "type": "stock",
        "code": "BRFS3",
        "name": "BRF SA",
        "price": 25.71,
        "sector": "Bens não duráveis",
        "volatility": 46.19,
        "dy": 0.0,
        "pvpa": 0.0,
        "appreciation": 185.73,
    },
    {
        "type": "stock",
        "code": "COGN3",
        "name": "COGNA",
        "price": 1.33,
        "sector": "Serviços comerciais",
        "volatility": 52.19,
        "dy": 0.0,
        "pvpa": 0.0,
        "appreciation": -52.05,
    },
]
FIIS = [
    {
        "type": "fii",
        "code": "MXRF11",
        "name": "FII MAXI RENCI ER",
        "price": 10.05,
        "sector": "Fundo de Papel",
        "volatility": 8.63,
        "dy": 12.45,
        "pvpa": 1.01,
        "appreciation": -6.42,
    },
    {
        "type": "fii",
        "code": "VGHF11",
        "name": "FII VALOR HECI ER",
        "price": 8.81,
        "sector": "Fundo de Tijolo",
        "volatility": 11.62,
        "dy": 13.21,
        "pvpa": 1.00,
        "appreciation": -5.94,
    },
    {
        "type": "fii",
        "code": "EGYR11",
        "name": "FII ENERGY CI",
        "price": 3.01,
        "sector": "Fundo de Tijolo",
        "volatility": 63.22,
        "dy": 0.00,
        "pvpa": 0.09,
        "appreciation": -54.12,
    },
    {
        "type": "fii",
        "code": "VGIR11",
        "name": "FII VALREIIICI",
        "price": 9.86,
        "sector": "Fundo de Papel",
        "volatility": 9.95,
        "dy": 13.27,
        "pvpa": 1.01,
        "appreciation": 5.68,
    },
    {
        "type": "fii",
        "code": "XPSF11",
        "name": "FII XP SELECCI ER",
        "price": 7.53,
        "sector": "Fundo de Fundos",
        "volatility": 12.88,
        "dy": 12.51,
        "pvpa": 0.87,
        "appreciation": -12.15,
    },
    {
        "type": "fii",
        "code": "KISU11",
        "name": "FII KILIMA CI ER",
        "price": 8.14,
        "sector": "Fundo de Fundos",
        "volatility": 11.98,
        "dy": 10.97,
        "pvpa": 0.94,
        "appreciation": -4.79,
    },
    {
        "type": "fii",
        "code": "MCHF11",
        "name": "FII MAUA HF CI",
        "price": 9.05,
        "sector": "Fundo de Papel",
        "volatility": 24.31,
        "dy": 5.27,
        "pvpa": 0.95,
        "appreciation": -2.47,
    },
    {
        "type": "fii",
        "code": "VSLH11",
        "name": "FII VERS CRICI",
        "price": 3.40,
        "sector": "Fundo de Papel",
        "volatility": 33.77,
        "dy": 13.11,
        "pvpa": 0.73,
        "appreciation": 4.42,
    },
    {
        "type": "fii",
        "code": "KNCR11",
        "name": "FII KINEA RICI ER",
        "price": 104.93,
        "sector": "Fundo de Papel",
        "volatility": 8.03,
        "dy": 11.70,
        "pvpa": 0.98,
        "appreciation": 8.19,
    },
    {
        "type": "fii",
        "code": "VINO11",
        "name": "FII VINCI OFCI ER",
        "price": 6.04,
        "sector": "Fundo de Tijolo",
        "volatility": 25.40,
        "dy": 11.68,
        "pvpa": 0.80,
        "appreciation": -33.30,
    },
    {
        "type": "fii",
        "code": "KNIP11",
        "name": "FII KINEA IPCI ER",
        "price": 95.95,
        "sector": "Fundo de Papel",
        "volatility": 7.94,
        "dy": 10.08,
        "pvpa": 0.97,
        "appreciation": 5.74,
    },
    {
        "type": "fii",
        "code": "HCTR11",
        "name": "FII HECTARE CI",
        "price": 29.45,
        "sector": "Fundo de Papel",
        "volatility": 48.10,
        "dy": 13.95,
        "pvpa": 0.67,
        "appreciation": -32.71,
    },
    {
        "type": "fii",
        "code": "SARE11",
        "name": "FII SANT RENCI ER",
        "price": 40.29,
        "sector": "Fundo Híbrido",
        "volatility": 25.54,
        "dy": 11.57,
        "pvpa": 0.62,
        "appreciation": -26.37,
    },
    {
        "type": "fii",
        "code": "RBRR11",
        "name": "FII RBRHGRADCI",
        "price": 91.11,
        "sector": "Fundo de Papel",
        "volatility": 12.54,
        "dy": 10.19,
        "pvpa": 0.90,
        "appreciation": 3.56,
    },
    {
        "type": "fii",
        "code": "CPTS11",
        "name": "FII CAPI SECCI",
        "price": 8.25,
        "sector": "Fundo de Papel",
        "volatility": 14.75,
        "dy": 10.49,
        "pvpa": 0.90,
        "appreciation": -2.48,
    },
    {
        "type": "fii",
        "code": "IRDM11",
        "name": "FII IRIDIUM CI",
        "price": 71.59,
        "sector": "Fundo de Papel",
        "volatility": 13.34,
        "dy": 12.69,
        "pvpa": 0.97,
        "appreciation": -9.65,
    },
    {
        "type": "fii",
        "code": "BTCI11",
        "name": "FII BTG CRI CI",
        "price": 9.96,
        "sector": "Fundo de Papel",
        "volatility": 6.0,
        "dy": 11.16,
        "pvpa": 0.88,
        "appreciation": 7.34,
    },
    {
        "type": "fii",
        "code": "TORD11",
        "name": "FII TORDE EICI",
        "price": 1.26,
        "sector": "Fundo Híbrido",
        "volatility": 34.06,
        "dy": 0.0,
        "pvpa": 0.39,
        "appreciation": -52.19,
    },
    {
        "type": "fii",
        "code": "CARE11",
        "name": "FII DEA CARECI",
        "price": 1.60,
        "sector": "Fundo de Tijolo",
        "volatility": 45.89,
        "dy": 0.00,
        "pvpa": 0.00,
        "appreciation": -16.32,
    },
    {
        "type": "fii",
        "code": "BCFF11",
        "name": "FII BC FFII CI",
        "price": 8.27,
        "sector": "Fundo de Fundos",
        "volatility": 17.93,
        "dy": 9.89,
        "pvpa": 0.86,
        "appreciation": -6.53,
    },
]
